var subicon = '<i class="fa fa-desktop" aria-hidden="true"></i>';
var leftNav = [{
	"title": "仓储业务",
	"icon": "fa-cogs",
	"href": "",
	"spread": false,
	"children": [{
		"title": "新增出库",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/cangChuYeWu/xinZengChuKu.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "新增入库",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/cangChuYeWu/xinZengRuKu.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "新增过户",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/cangChuYeWu/xinZengGuoHu.jsp",
		"spread": false,
		"show": true
	}]
}, {
	"title": "结算中心",
	"icon": "fa-file-text",
	"href": "",
	"spread": false,
	"children": [{
		"title": "日结订单明细",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/jieSuanZhongXin/dingDanJieSuan.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "结算汇总",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/jieSuanZhongXin/jieSuanHuiZong.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "月结缴费记录",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/jieSuanZhongXin/jiaoFeiJiLu.jsp",
		"spread": false,
		"show": true
	}]
}, {
	"title": "数据中心",
	"icon": "fa-money",
	"href": "",
	"spread": false,
	"children": [{
		"title": "订单查询",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/shuJuZhongXin/dingDanChaXun.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "作废订单查询",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/shuJuZhongXin/zuoFeiDingDanChaXun.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "收发存报表",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/shuJuZhongXin/shouFaCun.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "库存查询",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/shuJuZhongXin/keHuKuCunChaXun.jsp",
		"spread": false,
		"show": true
	}]
}, {
	"title": "系统设置",
	"icon": "fa-database",
	"href": "",
	"spread": false,
	"children": [{
		"title": "用户资料",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/xiTongSheZhi/keHuXinXi_XiangQing.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "修改密码",
		"icon": subicon,
		"href": "/XGProject/xxcc-sl/clientPage/xiTongSheZhi/passWord.jsp",
		"spread": false,
		"show": true
	}, {
		"title": "注销系统",
		"icon": subicon,
		"href": "javascript:;",
		"spread": false,
		"show": true
	}]
}];