var subicon = '<i class="fa fa-desktop" aria-hidden="true"></i>';
var leftNav = [{
   "title": "首页",
   "icon": "fa-tachometer",
   "href": "",
   "spread": true,
   "children": [{
      "title": "待处理订单",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/home/dingDanDaiChuLi.jsp",
      "spread": false
   }, {
      "title": "配送订单",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/home/delivery.jsp",
      "spread": false
   }, {
      "title": "在线用户",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/home/ZaiXianYongHu.jsp",
      "spread": false,
      "show": true
   }]
}, {
   "title": "仓储业务",
   "icon": "fa-cogs",
   "href": "",
   "spread": false,
   "children": [{
      "title": "新增出库",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/xinZengChuKu.jsp",
      "spread": false
   }, {
      "title": "新增入库",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/xinZengRuKu.jsp",
      "spread": false
   }, {
      "title": "新增过户",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/xinZengGuoHu.jsp",
      "spread": false
   }, {
      "title": "新增盘库",
      "icon": subicon,
      "href": "page/cc-caozuo/panku.html",
      "spread": false
   }, {
      "title": "新增挪库",
      "icon": subicon,
      "href": "page/cc-caozuo/nuoku.html",
      "spread": false
   }, {
      "title": "新增短倒",
      "icon": subicon,
      "href": "page/cc-caozuo/duandao.html",
      "spread": false
   }, {
      "title": "订单操作",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/dingDanCaoZuo.jsp",
      "spread": false
   }, {
      "title": "订单过磅",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/dingDanGuoBang.jsp",
      "spread": false
   }, {
      "title": "订单审核",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/dingDanShenHe.jsp",
      "spread": false
   }, {
      "title": "订单收费",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/dingDanShouFei.jsp",
      "spread": false
   }, {
      "title": "盘库审核",
      "icon": subicon,
      "href": "page/cc-caozuo/pankushenhe.html",
      "spread": false
   }, {
      "title": "冻结客户库存",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/keHuKuCunDongJie.jsp",
      "spread": false
   }, {
      "title": "盘点客户库存",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-caozuo/keHuKuCunPanDian.jsp",
      "spread": false
   }]
}, {
   "title": "仓储资料",
   "icon": "fa-file-text",
   "href": "",
   "spread": false,
   "children": [{
      "title": "库区管理",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/kuqu.jsp",
      "spread": false
   }, {
      "title": "库位管理",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/kuwei.jsp",
      "spread": false
   }, {
      "title": "货物类型",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/pinlei.jsp",
      "spread": false
   }, {
      "title": "货物规格",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/guige.jsp",
      "spread": false
   }, {
      "title": "货物材质",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/caizhi.jsp",
      "spread": false
   }, {
      "title": "货物属性",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/shuxing.jsp",
      "spread": false
   }, {
      "title": "货物产地",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/chandi.jsp",
      "spread": false
   }, {
      "title": "计件单位",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/danwei.jsp",
      "spread": false
   }, {
      "title": "货物名称",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/mingcheng.jsp",
      "spread": false
   }, {
      "title": "今日钢价",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/cc-ziliao/jinRiGangJia.jsp",
      "spread": false
   }]
}, {
   "title": "财务管理",
   "icon": "fa-money",
   "href": "",
   "spread": false,
   "children": [{
      "title": "日收费明细",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/riJieShouFeiMingXi.jsp",
      "spread": false
   }, {
      "title": "下站费记录",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/xiaZhanFeiJiLu.jsp",
      "spread": false
   }, {
      "title": "月结费用结算",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/yueJieFeiYongJieSuan.jsp",
      "spread": false
   }, {
      "title": "月结收费",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/yueJieShouFei.jsp",
      "spread": false
   }, {
      "title": "月结收费记录",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/yueJieShouFeiJiLu.jsp",
      "spread": false
   }, {
      "title": "费用类型",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/costType.jsp",
      "spread": false
   }, {
      "title": "支付方式",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/payment.jsp",
      "spread": false
   }, {
      "title": "票据类型",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/caiwu/bill.jsp",
      "spread": false
   }]
}, {
   "title": "数据中心",
   "icon": "fa-database",
   "href": "",
   "spread": false,
   "children": [{
      "title": "订单查询",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/dingDanChaXun.jsp",
      "spread": false
   }, {
      "title": "客户库存查询",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/keHuKuCunChaXun.jsp",
      "spread": false
   }, {
      "title": "库位库存查询",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/kuWeiKuCunChaXun.jsp",
      "spread": false
   }, {
      "title": "历史库存查询",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/liShiKuCunChaXun.jsp",
      "spread": false
   }, {
      "title": "挪库查询",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/nuoKuChaXun.jsp",
      "spread": false
   }, {
      "title": "短倒查询",
      "icon": subicon,
      "href": "page/404.html",
      "spread": false
   }, {
      "title": "盘库查询",
      "icon": subicon,
      "href": "page/404.html",
      "spread": false
   }, {
      "title": "收发存报表",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/shouFaCun.jsp",
      "spread": false
   }, {
      "title": "工作量统计",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/gongZuoLiangTongJi.jsp",
      "spread": false
   }, {
      "title": "货物批次表",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/data/huoWuPiCiChaXun.jsp",
      "spread": false
   }, {
      "title": "订单修改审批",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/home/shenPi.jsp",
      "spread": false
   }]
}, {
   "title": "客户管理",
   "icon": "fa-users",
   "href": "",
   "spread": false,
   "children": [{
      "title": "客户信息",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/client/keHuXinXi.jsp",
      "spread": false
   }, {
      "title": "注册客户",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/client/keHuZhuCe.jsp",
      "spread": false
   }]
}, {
   "title": "系统管理",
   "icon": "fa-cog",
   "href": "",
   "spread": false,
   "children": [{
      "title": "部门管理",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/system/department.jsp",
      "spread": false
   }, {
      "title": "班组管理",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/system/team.jsp",
      "spread": false
   }, {
      "title": "操作人员",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/system/operator.jsp",
      "spread": false
   }, {
      "title": "装卸人员",
      "icon": subicon,
      "href": "page/system/user.html",
      "spread": false
   }, {
      "title": "角色权限",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/system/jiaoSeQuanXian.jsp",
      "spread": false
   }, {
      "title": "系统日志",
      "icon": subicon,
      "href": "/XGProject/xxcc-sl/page/system/xiTongRiZhi.jsp",
      "spread": false
   }, {
      "title": "初始化客户库存",
      "icon": subicon,
      "href": "page/404.html",
      "spread": false
   }, {
      "title": "初始化库位库存",
      "icon": subicon,
      "href": "page/404.html",
      "spread": false
   }]
}];